### ISSUE TITLE
New world generation bug

### ISSUE THREAD

**Issue by Ryorama** [Ryorama/Terrariamod#3]
Currently, there is a bug that causes the game to freeze when creating a new world. The only work around is to reload Minecraft and keep loading the world until it finishes and loads. This will be fixed soon

**Comment by Powermonkey00** [comment]
Don't know if this helps any but here's the output from attempting to start a terrariamod server.

2021-01-17 13:41:36,635 main WARN Advanced terminal features are not available in this environment
←[32m[13:41:36] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 28.2.23, --fml.mcpVersion, 20190829.143755, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge]
←[m←[32m[13:41:36] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 4.1.0+62+5bfa59b starting: java version 1.8.0_271 by Oracle Corporation
←[m←[32m[13:41:37] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
←[m←[32m[13:41:38] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
←[m←[33m[13:41:46] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
←[m←[33m[13:41:46] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
←[m←[33m[13:41:46] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
←[m←[33m[13:41:46] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
←[m←[33m[13:41:46] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
←[m←[32m[13:41:47] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.14.4
←[m←[32m[13:41:47] [modloading-worker-11/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 28.2.23, for MC 1.14.4 with MCP 20190829.143755
←[m←[32m[13:41:47] [modloading-worker-11/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v28.2.23 Initialized
←[m←[32m[13:41:47] [modloading-worker-9/INFO] [STDOUT/]: [kmerrill285.trewrite.Trewrite:<init>:102]: false
←[m←[1;31m[13:41:49] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
←[m←[1;31m[13:41:49] [Server thread/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
        Index: 9
        Listeners:
                0: NORMAL
                1: ASM: class kmerrill285.trewrite.world.dimension.DimensionRegistry onDimensionRegistryEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
                2: ASM: class kmerrill285.trewrite.world.biome.surfacebuilders.SurfaceBuilders onRegisterBiomes(Lnet/minecraftforge/event/RegistryEvent$Register;)V
                3: ASM: class kmerrill285.trewrite.world.biome.BiomeT onRegisterBiomes(Lnet/minecraftforge/event/RegistryEvent$Register;)V
                4: ASM: class kmerrill285.trewrite.paintings.PaintingsT registerPaintings(Lnet/minecraftforge/event/RegistryEvent$Register;)V
                5: ASM: class kmerrill285.trewrite.items.ItemsT registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
                6: ASM: class kmerrill285.trewrite.entities.EntitiesT registerEntities(Lnet/minecraftforge/event/RegistryEvent$Register;)V
                7: ASM: class kmerrill285.trewrite.core.sounds.TAudio registerAudio(Lnet/minecraftforge/event/RegistryEvent$Register;)V
                8: ASM: class kmerrill285.trewrite.core.inventory.container.Containers registerContainers(Lnet/minecraftforge/event/RegistryEvent$Register;)V
                9: ASM: class kmerrill285.trewrite.blocks.BlocksT registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
                10: ASM: class kmerrill285.stackeddimensions.blocks.BlockRegistry registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71)
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:102)
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80)
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at kmerrill285.trewrite.blocks.BlocksT.registerBlocks(BlocksT.java:461)
        at net.minecraftforge.eventbus.ASMEventHandler_37_BlocksT_registerBlocks_Register.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
        at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
        at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
        at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
        at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125)
        at java.util.ArrayList.forEach(Unknown Source)
        at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125)
        at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
        at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197)
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189)
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:967)
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189)
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600)
        at java.lang.Thread.run(Unknown Source)

←[m←[1;31m[13:41:49] [Server thread/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:block> dispatch for modid trewrite
java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge-1.14.4-28.2.23.jar:28.2] {}
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:102) ~[modlauncher-4.1.0.jar:4.1.0+62+5bfa59b] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80) ~[modlauncher-4.1.0.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-4.1.0.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241) ~[modlauncher-4.1.0.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128) ~[modlauncher-4.1.0.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-4.1.0.jar:?] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271] {}
        at kmerrill285.trewrite.blocks.BlocksT.registerBlocks(BlocksT.java:461) ~[?:1.0] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_37_BlocksT_registerBlocks_Register.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:28.2] {re:classloading}
        at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_271] {}
        at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125) ~[?:?] {re:classloading}
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_271] {}
        at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189) ~[?:?] {re:classloading}
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:967) [?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189) [?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) [?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}
←[m←[1;31m[13:41:49] [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found
←[m←[1;31m[13:41:49] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Example Mod (trewrite) encountered an error during the load_registries event phase
?7Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189) ~[?:?] {re:classloading}
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:967) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}
←[m←[1;31m[13:41:49] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: E:\games\.technic\modpacks\just-terrariamod\.\crash-reports\crash-2021-01-17_13.41.49-server.txt
←[m←[32m[13:41:49] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
←[m←[32m[13:41:49] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
←[m←[1;31m[13:41:49] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:182) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:981) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:523) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:555) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:544) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

**Comment by Powermonkey00** [comment]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/17/21 1:41 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Example Mod (trewrite) encountered an error during the load_registries event phase
§7Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:967) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1887001336 bytes (1799 MB) / 3133669376 bytes (2988 MB) up to 7624720384 bytes (7271 MB)
	CPUs: 12
	JVM Flags: 0 total; 
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.23
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.23-server.jar Minecraft {minecraft@1.14.4 LOAD_REGISTRIES}
		TerrariaMod+v1.1-1.14.4.jar Example Mod {trewrite@1.0 ERROR}
		forge-1.14.4-28.2.23-universal.jar Forge {forge@28.2.23 LOAD_REGISTRIES}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Ryorama** [comment]
This no longer exists in the 1.17 port. As for the 1.14.4 version I might still try to locate the issue. I'm going to close this issue for now, but if anyone has extra info please open a new issue.
